services:
  db:
    build:
      context: postgres
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "mydatabase"]
      interval: 5s
      timeout: 20s
      retries: 5
      start_period: 5s
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  postgraphile:
    build:
      context: postgraphile
      dockerfile: Dockerfile
    # healthcheck:
    #   test: ["curl", "-f", "http://localhost:5001", "||", "exit 1"]
    restart: on-failure:3
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - "5001:5000"
    networks:
      - mynetwork
  app:
    build: .
    healthcheck:
      test: ["CMD-SHELL", "curl", "-sSf", "http:/localhost:8080", "||", "exit", "1"]
    ports:
      - "8080:8080"
    networks:
      - mynetwork
  # k6:
  #   image: loadimpact/k6
  #   depends_on:
  #     - app
  #   volumes:
  #     - ./test.js:/test/test.js
  #   command: run /test/test.js
  #   deploy:
  #     replicas: 0 # Don't auto start service on docker up command
  #   networks:
  #     - mynetwork
  #
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
    driver: bridge
