services:
  db:
    build:
      context: postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  postgraphile:
    build:
      context: postgraphile
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - mynetwork
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
    driver: bridge
