services:
  db:
    build:
      context: postgres
      dockerfile: Dockerfile
    restart: on-failure:3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "$${POSTGRES_DB}", "-U", "$${POSTGRES_USER}"]
      interval: 5s
      timeout: 20s
      retries: 5
      start_period: 5s
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - mynetwork
  postgraphile:
    build:
      context: postgraphile
      dockerfile: Dockerfile
    restart: on-failure:3
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - "5001:5001"
    networks:
      - mynetwork
  app:
    build: .
    restart: on-failure:3
    ports:
      - "8080:8080"
      - "8545:8545" # Anvil
    depends_on:
      - postgraphile
    networks:
      - mynetwork
  # k6:
  #   image: loadimpact/k6
  #   depends_on:
  #     - app
  #   volumes:
  #     - ./test.js:/test/test.js
  #   command: run /test/test.js
  #   deploy:
  #     replicas: 0 # Don't auto start service on docker up command
  #   networks:
  #     - mynetwork
  #
  adminer:
    image: adminer
    ports:
      - "5101:8080"
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
    driver: bridge
