services:
  postgres-raw:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-d",
          "$${POSTGRES_DB}",
          "-U",
          "$${POSTGRES_USER}",
        ]
