name: CI

on: push

permissions:
  contents: write

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Clang
      run: sudo apt-get update && sudo apt-get install -y clang

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
          version: latest

    - name: Check generate
      run: make check-gen

    - name: Build
      run: make build

    - name: Test
      run: make test

  release:
    name: Release
    runs-on: ubuntu-22.04
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Trim CHANGELOG.md
      run: sed -e '0,/^##[^#]/d' -e '/^##[^#]/,$d' -i CHANGELOG.md
  
    - name: Publish Github release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        body_path: CHANGELOG.md

  releases-matrix:
    name: Build binaries for release
    runs-on: ubuntu-latest
    needs: [release]
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
        exclude:
        - goarch: arm64
          goos: windows
    steps:
    - uses: actions/checkout@v4

    - uses: wangyoucao577/go-release-action@v1
      with:
        overwrite: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        extra_files: CHANGELOG.md LICENSE README.md
  
  release-darwin-arm64:
    name: Build binaries for darwin arm64
    runs-on: macos-14
    needs: [release]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Compile arm64
      run: go build -tags "darwin arm64"

  # release-darwin-amd64:
  #   name: Build binaries for Mac Intel
  #   runs-on: macos-13-large
  #   needs: [release]

  #   steps:
  #   - uses: actions/checkout@v4

  #   - name: Set up Go
  #     uses: actions/setup-go@v4
  #     with:
  #       go-version: '1.21'
    
  #   - name: Install deps
  #     run: |
  #       brew install sqlite3
  #       brew upgrade icu4c

  #   - name: Compile amd64
  #     run: go build -tags "darwin amd64"
