name: Release

on:
  release:
    types: [prereleased]

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
        - goarch: arm64
          goos: windows
    steps:
    - uses: actions/checkout@v4

    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.21.5.linux-amd64.tar.gz"
        project_path: "./"
        binary_name: "nonodo"
        extra_files: LICENSE README.md
